### ISSUE TITLE
Feature request: Add new command to create changes file

### ISSUE THREAD

**Issue by haukkari** [ypjama/conflictless-keepachangelog#2]
## Description

It would enhance the functionality of this tool if a command were introduced to facilitate the creation of empty changes files. I propose the addition of a new command, `create` which would serve the purpose of generating these empty changes files.

## Arguments for the create command

Here's a list of arguments that this command could support:

argument|allowed values|description
---|---|---
format|`yml,json`|Set the changes file format. Only one format is allowed
types|`added,changed,deprecated,removed,fixed,security`|Initialize empty changes file with these type. You can add multiple types with separating them with comma 
dir| `any_string` | Name of the directory where the new file is created. By default it's `changes`. Command will fail if directory doesn't exists.
name| `any_string` | Name of the changes file. If empty it uses the git branch name. :thinking:  What if on main branch, is it good idea to create `changes/main.yml` file.

## Examples

``` bash
conflictess create --format yml --dir custom_changes --name foo --types added,changed
```

This command would would create following file `custom_changes/foo.yml`:

```yaml
added:
  - 
changed:
  - 
````

**Comment by ypjama** [comment]
Seems useful. I'll see what I can do!
